import numpy as np

def combiner_for_prose(raw_embedding : np.array , method: str)-> np.array :
    """
    Given ad embedding generated by "prose" (i.e. a matrix (sequence len)*(100) where each 100-dim vector is the embedding for a single nucleotide)
    it returns an embedding for the entire protein using some combination methods.
    """

    if method == "average":
        return raw_embedding.mean(axis=0)  # mean between all amminoacids
    elif method == "max":
        return raw_embedding.max(axis=0) 
    elif method == "sum":
        return raw_embedding.sum(axis=0)
    else:
        raise Exception(f"Unknown combining method: {method} for prose")
    

def combiner_for_dnabert(raw_embedding: np.array, method: str) -> np.array:
    """
    Given ad embedding generated by "dnabert" (i.e. a matrix (sequence len % 512)*(768) where each 768-dim vector is the embedding of a consecutive subsequence of 512 nucleotides)
    it returns an embedding for the entire protein using some combination methods.
    """
    if method == "average":
        return raw_embedding.mean(axis=0)  # mean between the embeddings of the subsequences
    else:
        raise Exception(f"Unknown combining method: {method} for dnabert")
    

def combiner_for_rep(raw_embedding : np.array, method: str = "none") -> np.array:
    """
    Given ad embedding generated by "embedding_reproduction" (i.e. an 64-dim array)
    it returns an embedding for the entire protein, i.e. a simple copy of the array.
    """

    return raw_embedding