name: bioemb3
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - biopython=1.78
  - blas=1.0
  - bottleneck=1.3.5
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cudatoolkit=10.2.89
  - fftw=3.3.9
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - h5py=3.7.0
  - hdf5=1.10.6
  - intel-openmp=2021.4.0
  - joblib=1.1.1
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.0
  - libuv=1.40.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1s
  - packaging=22.0
  - pandas=1.5.2
  - pillow=9.3.0
  - pip=22.3.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - pytorch=1.8.1
  - pytz=2022.7
  - readline=8.2
  - scikit-learn=1.2.0
  - scipy=1.9.3
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
